
export const regions = {
    1: 'stranac u Bosni i Hercegovini', 2: 'stranac u Crnoj Gori', 3: 'stranac u Hrvatskoj', 4: 'stranac u Severnoj Makedoniji', 5: 'stranac u Sloveniji', 6: 'Nedefinisano', 7: 'stranac u Srbiji bez pokrajina', 8: 'stranac u Vojvodini', 9: 'stranac na Kosovu i Metohiji',
    10: 'Banja Luka', 11: 'Bihac', 12: 'Doboj', 13: 'Gorazde;', 14: 'Livno', 15: 'Mostar', 16: 'Prijedor', 17: 'Sarajevo', 18: 'Tuzla', 19: 'Zenica',
    20: 'Crna Gora', 21: 'Podgorica', 22: 'Crna Gora', 23: 'Crna Gora', 24: 'Herceg Novi', 25: 'Crna Gora', 26: 'Niksic', 27: 'Berane', 28: 'Crna Gora', 29: 'Pljevlja',
    30: 'Osijek, Slavonija', 31: 'Bjelovar, Vjerovitica, Koprivnica, Pakrac, Podravina region', 32: 'Varazdin, Medjimurje region', 33: 'Zagreb', 34: 'Karlovac', 35: 'Gospic, Lika region', 36: 'Rijeka, Pula, Istra, Primorje region', 37: 'Sisak, Banovina region', 38: 'Split, Zadar, Dubrovnik, Dalmacija region', 39: 'Mesano',
    40: 'Makedonija', 41: 'Bitola', 42: 'Kumanovo', 43: 'Ohrid', 44: 'Prilep', 45: 'Skopje', 46: 'Strumica', 47: 'Tetovo', 48: 'Veles', 49: 'Stip',
    50: 'Slovenija', 51: 'Slovenija', 52: 'Slovenija', 53: 'Slovenija', 54: 'Slovenija', 55: 'Slovenija', 56: 'Slovenija', 57: 'Slovenija', 58: 'Slovenija', 59: 'Slovenija',
    60: 'Nedefinisano', 61: 'Nedefinisano', 62: 'Nedefinisano', 63: 'Nedefinisano', 64: 'Nedefinisano', 65: 'Nedefinisano', 66: 'Nedefinisano', 67: 'Nedefinisano', 68: 'Nedefinisano', 69: 'Nedefinisano',
    70: 'Centralna Srbija', 71: 'Beograd (Grad Beograd: Stari Grad, Savski Venac, Voždovac, Vračar, Palilula, Zvezdara, Rakovica, Čukarica, Novi Beograd, Zemun, Mladenovac, Barajevo, Grocka, Obrenovac, Sopot, Lazarevac)', 72: 'Šumadija i Pomoravlje region (Šumadijski okrug: Aranđelovac, Batočina, Knić, Kragujevac, Rača, Lapovo, Topola), (Pomoravski okrug: Despotovac, Paraćin, Rekovac, Jagodina, Svilajnac, Ćuprija)', 73: 'Niš region (Nišavski okrug: Aleksinac, Svrljig, Niš, Gadžin Han, Doljevac, Merošina, Ražanj), (Pirotski okrug: Babušnica, Bela Palanka, Dimitrovgrad, Pirot), (Toplički okrug: Blace, Žitorađa, Prokuplje, Kuršumlija)', 74: 'Južna Morava region (Jablanički okrug: Leskovac, Vlasotince, Medveđa, Lebane, Bojnik, Crna Trava), (Pčinjski okrug: Vranje, Bujanovac, Surdulica, Bosilegrad, Preševo, Trgovište, Vladičin Han)', 75: ' Zaječar region (Zaječarski okrug: Zaječar, Boljevac, Knjaževac, Sokobanja), (Borski okrug: Bor, Majdanpek, Kladovo, Negotin)', 76: 'Podunavlje region (Podunavski okrug: Smederevska Palanka, Velika Plana, Smederevo), (Braničevski okrug: Veliko Gradište, Kučevo, Petrovac na Mlavi, Požarevac, Žagubica, Golubac, Žabari, Malo Crniće)', 77: 'Podrinje i Kolubara regions (Mačvanski okrug: Loznica, Krupanj, Ljubovija, Šabac, Bogatić, Koceljeva, Vladimirci, Mali Zvornik), (Kolubarski okrug: Valjevo, Lajkovac, Ljig, Ub, Osečina, Mionoca)', 78: 'Kraljevo region (Raški okrug: Kraljevo, Vrnjačka Banja, Novi Pazar, Raška, Tutin), (Moravički okrug: Gornji Milanovac, Čačak, Ivanjica, Lučani), (Rasinski okrug: Aleksandrovac, Brus, Kruševac, Trstenik, Varvarin, Ćićevac)', 79: 'Užice region (Zlatiborski okrug: Arilje, Bajina Bašta, Kosjerić, Nova Varoš, Požega, Priboj, Prijepolje, Sjenica, Užice, Čajetina)',
    80: 'Novi Sad region (Južnobački okrug: Bač, Bačka Palanka, Bački Petrovac, Vrbas, Žabalj, Novi Sad, Srbobran, Sremski Karlovci, Temerin, Titel, Bečej, Beočin)', 81: 'Sombor region (Zapadnobački okrug: Apatin, Kula, Odžaci, Sombor)', 82: 'Subotica region (Severnobački okrug: Bačka Topola, Subotica, Mali Iđoš)', 83: 'Vrbas', 84: 'Vojvodina', 85: 'Zrenjanin region (Srednjebanatski okrug: Zrenjanin, Nova Crnja, Novi Bečej, Sečanj, Žitište)', 86: 'Pančevo region (Južnobanatski okrug: Alibunar, Bela Crkva, Vršac, Kovačica, Kovin, Pančevo, Opovo, Plandište)', 87: 'Kikinda region (Severnobanatski okrug: Ada, Kikinda, Kanjiža, Novi Kneževac, Senta, Čoka)', 88: 'Ruma region (Sremski okrug: Inđija, Pećinci, Ruma, Sremska Mitrovica, Stara Pazova, Šid, Irig)', 89: 'Sremska Mitrovica region (Sremski okrug: Inđija, Pećinci, Ruma, Sremska Mitrovica, Stara Pazova, Šid, Irig)',
    90: 'Autonomna pokrajina Kosovo i Metohija', 91: 'Priština region (Kosovski okrug: Priština, Obilić, Podujevo, Štrpce, Lipljan, Glogovac, Kačanik, Kosovo Polje, Uroševac, Štimlje)', 92: 'Kosovska Mitrovica region (Kosovsko Mitrovački okrug: Kosovska Mitrovica, Zvečan, Leposavić, Zubin Potok, Vučitrn, Srbica)', 93: 'Peć region (Pećki okrug: Peć, Istok, Klina)', 94: 'Đakovica region (Pećki okrug: Dečani, Đakovica)', 95: 'Prizren region (Prizrenski okrug: Gora-Dragaš, Orahovac, Prizren, Suva Reka)', 96: 'Kosovsko Pomoravski okrug: (Gnjilane, Kosovska Kamenica, Vitina, Novo Brdo)', 97: 'Kosovo i Metohija', 98: 'Kosovo i Metohija', 99: 'Kosovo i Metohija'
};